NotPlaterLocals = {
	-- Status
	["Enemy player/npc name plates are now visible."] = "Enemy player/npc name plates are now visible.",
	["Enemy player/npc name plates are now hidden."] = "Enemy player/npc name plates are now hidden.",
	["Friendly player/npc name plates are now visible."] = "Friendly player/npc name plates are now visible.",
	["Friendly player/npc name plates are now hidden."] = "Friendly player/npc name plates are now hidden.",
	["All name plates are now visible."] = "All name plates are now visible.",
	["All name plates are now hidden."] = "All name plates are now hidden.",
	
	-- GUI
	["Enabled"] = "Enabled",
	["General"] = "General",
	["Position"] = "Position",
	["Bars"] = "Bars",
	["Bar texture"] = "Bar texture",
	["Background color"] = "Background color",
	["Hide background"] = "Hide background",
	["Casttime text"] = "Casttime text",
	["Castname text"] = "Castname text",
	["Threat differential text"] = "Threat differential text",
	["Threat number text"] = "Threat number text",
	["Cast spellicon"] = "Cast spellicon",
	["Shadow"] = "Shadow",
	["Healthbar"] = "Healthbar",
	["Castbar"] = "Castbar",
	["Health text"] = "Health text",
	["Positioning / Scaling"] = "Positioning / Scaling",
	["topright"] = "Topright",
	["bottomleft"] = "Bottomleft",
	["topleft"] = "Topleft",
	["bottomright"] = "Bottomright",
	["center"] = "Center",
	["top"] = "Top",
	["bottom"] = "Bottom",
	["left"] = "Left",
	["right"] = "Right",
	["Top Offset"] = "Top Offset",
	["Bottom Offset"] = "Bottom Offset",
	["Left Offset"] = "Left Offset",
	["Right Offset"] = "Right Offset",
	["Offset X"] = "Offset X",
	["Offset Y"] = "Offset Y",
	["Size X"] = "Size X",
	["Size Y"] = "Size Y",
	["Anker"] = "Anker",
	["Opacity"] = "Opacity",
	["Hide target border"] = "Hide target border",
	["Hide border"] = "Hide border",
	["Set the anker for the healthbar."] = "Set the anker for the healthbar.",
	["Raid icon"] = "Raid icon",
	["Boss icon"] = "Boss icon",
	["Nameplate stacking"] = "Nameplate stacking",
	["X stacking margin"] = "X stacking margin",
	["Y stacking margin"] = "Y stacking margin",
	["Overlapping castbars"] = "Overlapping castbars",
	["Only works if the nameplate is visible before you are in combat"] = "Only works if the nameplate is visible before you are in combat",
	["inherited"] = "Inherited",
	["background"] = "Background",
	["low"] = "Low",
	["medium"] = "Medium",
	["high"] = "High",
	["dialog"] = "Dialog",
	["fullscreen"] = "Fullscreen",
	["fullscreen dialog"] = "Fullscreen Dialog",
	["tooltip"] = "Tooltip",
	["border"] = "Border",
	["artwork"] = "Artwork",
	["overlay"] = "Overlay",
	["highlight"] = "Highlight",
	["Frame Strata"] = "Frame Strata",
	["Frame"] = "Frame",
	["Target Frame"] = "Target Frame",
	["Note: All settings here only work out of combat, because the frame cannot be changed in combat."] = "Note: All settings here only work out of combat (frame cannot be changed in combat).",

	
	["Custom texture to use for health and cast bars in name plates."] = "Custom texture to use for health and cast bars in name plates.",
	
	["Name text"] = "Name text",
	["Cast/Health text"] = "Cast/Health text",
	["Level text"] = "Level text",
	
	["Font name"] = "Font name",
	["Font color"] = "Font color",
	["Font name for the actual name text above name plate bars."] = "Font name for the actual name text above name plate bars.",

	["Font name for the level text."] = "Font name for the level text.",
	["Font name for the health bar text."] = "Font name for the health bar text.",
	["Font name for the cast bar text."] = "Font name for the cast bar text.",

	["Font size"] = "Font size",
	["Font border"] = "Font border",
	["Font opacity"] = "Font opacity",

	["Health text display"] = "Health text display",
	["Cast text display"] = "Cast text display",
	["Style of display for health bar text."] = "Style of display for health bar text.",
	["Style of display for cast bar text."] = "Style of display for cast bar text.",

	["Outline"] = "Outline",
	["Thick outline"] = "Thick outline",
	["Monochrome"] = "Monochrome",
	
	["Min / Max"] = "Min / Max",
	["Both"] = "Both",
	["Deficit"] = "Deficit",
	["Percent"] = "Percent",
	["None"] = "None",
	["Current / Max"] = "Current / Max",
	["Current"] = "Current",
	["Percent"] = "Percent",
	["Time left"] = "Time left",

	["Enable shadow"] = "Enable shadow",
	["Shadow color"] = "Shadow color",
	["Shadow offset X"] = "Shadow offset X",
	["Shadow offset Y"] = "Shadow offset Y",
	
	["Threat"] = "Threat",
	["Threat colors"] = "Threat colors",
	["First on Threat"] = "First on Threat",
	["Upper twenty percent on Threat"] = "Upper twenty percent on Threat",
	["Lower eighty percent on Threat"] = "Lower eighty percent on Threat",
	["Nameplate threat colors"] = "Nameplate threat colors",
	["Enable font"] = "Enable font",
	["Enable Nameplate Threat Colors"] = "Enable Nameplate Threat Colors",
	["Mode"] = "Mode",
	["Choose between healer or tank selection."] = "Choose between healer or tank selection.",
	["Healer / DPS"] = "Healer / DPS",
	["Tank"] = "Tank",
	["Threat DPS / healer colors"] = "Threat DPS / Healer Colors",
	["Aggro on You"] = "Aggro on You",
	["High Threat"] = "High Threat",
	["Default / No Aggro"] = "Default / No Aggro",
	["Threat tank colors"] = "Threat Tank Colors",
	["Tank no aggro"] = "Tank has no Aggro",
	["Dps close"] = "DPS is close on Threat",

	["Show nameplate visibility status"] = "Show nameplate visibility status",
	["Hide health bar border"] = "Hide health bar border",
	["Hide cast bar border"] = "Hide cast bar border",
	
	["A UI reload is required to make the border show back up again."] = "A UI reload is required to make the border show back up again.",
}